import Head from "next/head";
import styles from "../styles/home.module.css";
import Card from "./components/Card";
export default function Home() {
  const obj = [
    {
      title: "JBL E55BT KEY BLACK",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores, vitae.",
      price: 400,
      image: "/mp4.png"
    },
    {
      title: "JBL JR 310BK",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores, vitae.",
      price: 350,
      image: "/mp2.png"
    },
    {
      title: "JBL TUNE 750BTNS",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores, vitae.",
      price: 450,
      image: "/mp6.png"
    },
    {
      title: "JBL HORIZON SOME PRO",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores, vitae.",
      price: 299,
      image: "/mp5.png"
    },
  ];
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.home}>
        <div className={styles.container}>
          <div className={styles.productWrapper}>
            {obj.map((e, index) => {
              return (
                <Card
                  key={index}
                  title={e.title}
                  price={e.price}
                  desc={e.desc}
                  image={e.image}
                  obj={obj}
                />
              );
            })}
          </div>
        </div>
      </div>
    </>
  );
}
